### ISSUE TITLE
Doubt on demonstrating/run

### ISSUE THREAD

**Issue by jai9318** [riebl/artery_scenario_mt-its2017#1]

**Comment by jai9318** [comment]
Hello sir, 
Little bit of confusions while asking my queries. Apologise from my side

Sir I have downloaded these codes
Since I am new to this .

1) I need help that how to run / demonstrate.
Steps would ge helpful.
What should be the directory/path while running.
2) If I want to change anything in this demonstration or update where can I change. 
Thank you

**Comment by riebl** [comment]
This repository is tracked by riebl/artery as git submodule. You have already a copy of this scenario at *scenarios/mt-its2017* when you have installed Artery according to its install instructions. In particular, `git clone --recursive` makes sure that git submodule are downloaded as well. In Artery, the make target is called `run_mtits2017` to run this scenario.
